### PR TITLE
update the datacard maker and add a plotter feature

### PR DESCRIPTION
**Pull request by De-Cristo**
1. update the datacard maker so that the processes can be [grouped](https://github.com/De-Cristo/VHccPoCo/blob/vhbb_dev/params/shapemaker_vhbb_run3/Zll_Shape.yaml#L85-L90).
image

2. modify the datacard maker so that the data_obs can be correct (please double check because the original datacards can be wrong, or the new [codes](https://github.com/De-Cristo/VHccPoCo/blob/vhbb_dev/scripts/convertToRoot.py#L112-L119) can be wrong) 
image

3. Added a plot [feature](https://github.com/De-Cristo/VHccPoCo/blob/vhbb_dev/scripts/datacard_plotter.py)
image
Next step will be add new plot features to plot the systematic uncertainties.

### CODE REVIEW

**Comment by andreypz** [comment]
Thanks for the work, I will take a look.
However I don't think we want to merge muon and electron dataset for Data...

**Comment by De-Cristo** [comment]
Thanks.
I know that we are not merge muon and electron channel, the setup in step 1 will not effect the data if the regions are defined properly.
The change in step 2 is not for merge leptonic channels, but fix the procedure to make e.g. EraC+EraD+ErF histogram. Please double check.

**Comment by De-Cristo** [comment]
Thanks.
I know that we are not merge muon and electron channel, the setup in step 1 will not effect the data if the regions are defined properly.
The change in step 2 is not for merge leptonic channels, but fix the procedure to make e.g. EraC+EraD+ErF histogram. Please double check.

**Comment by andreypz** [comment]
Closing due to conflict. See #39 instead

**Pull request closed without merging**
