### PR TITLE
Update the main sample json

### PR DESCRIPTION
**Pull request by De-Cristo**
0, removed a lethal comma
1, added 2022 Era A, B for `DATA_SingleMuon`

### CODE REVIEW

**Comment by andreypz** [comment]
Do we really need Era A of 2022? 
I think this dataset does not have any good lumis for the analysis.

**Comment by andreypz** [comment]
I think Era A is 900GeV collisions: https://twiki.cern.ch/twiki/bin/view/CMS/PdmVRun3Analysis#2022_Era_definition

**Comment by De-Cristo** [comment]
Thanks for the link. It is reasonable to not include A and B. Will remove them in next commit

**Review by De-Cristo — COMMENTED** [review]
1. removed the added Era A and B samples.
2. start to change the XS of the signal samples according to the official twiki page, will apply on the other samples later.
3. add VHbb WLN channel, relevant modifications in commonselectors and VHbb workflow
4. add necessary yaml files in the `params`

**Comment by andreypz** [comment]
@De-Cristo Could you please fix the cross sections for VHcc processes, then I will merge this.

**Comment by De-Cristo** [comment]
sure I can.

May I ask if the xsec can take more than values? Maybe something like `0.8*0.58` can also work?

**Comment by andreypz** [comment]
I am not sure bout this, but you could just try and test by running the build-datasets script. Then look at the output json files

**Review by De-Cristo — COMMENTED** [review]
updated all the signal samples XS with XS(VH) * BR(V) * BR(H) @andreypz 

image

**Review by andreypz — APPROVED** [review]
Looks good

**Pull request merged**
